name: RNSketchCanvas CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint and Tests
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Yarn Install
        run: yarn install --immutable

      - name: Linting
        run: yarn lint

      - name: Typing
        run: yarn typecheck

      - name: Testing
        run: yarn test --coverage

      - name: Prepare Build
        run: yarn build
